Repository dotnet/reactive, pull requests merged in 2019-11, with the labels that each got.

#916 IxAsync.Timeout: propagate timeout cancellation to main source
  Ix.NET/Source/System.Interactive.Async.Tests/System/Linq/Operators/Timeout.cs
  Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Timeout.cs
Labels: [area] Ix, bug

#914 Change Ix.Async Amb() to cancel the losers, add unit tests
  Ix.NET/Source/System.Interactive.Async.Tests/System/Linq/Operators/Amb.cs
  Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Amb.cs
  Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Never.cs
Labels: [area] Ix, enhancement

#969 Handle the case when EventLoopScheduler gets disposed with in-flight items
  Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs
  Rx.NET/Source/tests/Tests.System.Reactive/Tests/Concurrency/EventLoopSchedulerTest.cs
Labels: [area] Rx, bug

#891 Simplified BaseBlocking, FirstBlocking, and LastBlocking
  Rx.NET/Source/src/System.Reactive/Linq/Observable/FirstLastBlocking.cs
  Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Blocking.cs
Labels: [area] Rx, enhancement

#1079 Serialize the dispose of Zip(IEnumerable) with MoveNext/Current
  Rx.NET/Source/src/System.Reactive/Linq/Observable/Zip.cs
  Rx.NET/Source/tests/Tests.System.Reactive/Tests/Linq/Observable/ZipTest.cs
Labels: [area] Rx, bug

#915 Ix: Do not dispose the enumerator while enumerating in the ToObservable operator.
  Ix.NET/Source/System.Linq.Async.Tests/System/Linq/Operators/ToObservable.cs
  Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToObservable.cs
Labels: [area] Ix, bug
